version: '3.8'

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:  
      - 3001:3001
    environment:
      NODE_ENV: production
    restart: unless-stopped
    command: node dist/index.cjs